# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bcste/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/bcste/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bcste/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10

In [3]:
a=np.zeros(10,dtype=int)

#### 4.  How to find the memory size of any array

In [4]:
a.size*a.itemsize #int item size is 4 bytes and float is 8

40

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
a=np.array([int(x==4) for x in range(10)])
print(a)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
a=np.array([x for x in range(10,50)])
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
a=a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a=np.arange(0,9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [10]:
a=np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [12]:
a=np.random.random((3,3,3))
print(a)

[[[0.15234551 0.82629568 0.37891855]
  [0.72711786 0.93784619 0.2268625 ]
  [0.9103999  0.02228983 0.20162474]]

 [[0.12112591 0.84599793 0.81137979]
  [0.49384392 0.86341269 0.14149539]
  [0.28066025 0.3357771  0.39064159]]

 [[0.23976591 0.3182653  0.91858272]
  [0.36313917 0.99096065 0.72064194]
  [0.5703217  0.9942594  0.70677261]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
a=np.random.random((10,10))
print(a)
print("Min and Max are",np.min(a),np.max(a))

[[0.60125116 0.5926346  0.18718626 0.29709432 0.59873643 0.10490366
  0.84776515 0.8730703  0.71972346 0.48097559]
 [0.30931838 0.53828525 0.74595959 0.53995629 0.74338294 0.99986038
  0.18092099 0.17967596 0.80060848 0.08203192]
 [0.50719484 0.10366109 0.11714836 0.58682055 0.2689782  0.34823642
  0.21124604 0.34114743 0.91545749 0.34244371]
 [0.10732553 0.14445238 0.20081583 0.39881511 0.32100305 0.69933714
  0.64333391 0.74822431 0.21192191 0.07040232]
 [0.45122004 0.25871174 0.0802952  0.23247695 0.5944171  0.88414916
  0.98725781 0.71199669 0.73490908 0.68243651]
 [0.16247364 0.23653101 0.13561239 0.88774205 0.90380596 0.50230462
  0.53544179 0.14080302 0.5716626  0.20759052]
 [0.37329341 0.06928443 0.13909905 0.4889268  0.05700325 0.45425197
  0.8399738  0.5718013  0.31740084 0.63923715]
 [0.30845309 0.39184739 0.88219388 0.9765553  0.84296523 0.63570036
  0.53135988 0.60761164 0.47305804 0.69372095]
 [0.92879248 0.1572505  0.47181024 0.14914506 0.84898857 0.31595646
  0.11967176

#### 14. Create a random vector of size 30 and find the mean value

In [14]:
a=np.random.random(30)
print(a)
print(np.mean(a))

[0.16054393 0.1446069  0.45634764 0.93490192 0.79133455 0.05470844
 0.16291313 0.93884983 0.03994329 0.4727968  0.78482585 0.80752305
 0.80988585 0.30287542 0.55482345 0.89041882 0.99562372 0.66652731
 0.50612678 0.29585193 0.71222631 0.14672145 0.02135753 0.32460508
 0.99193136 0.53467505 0.03928686 0.23800661 0.8399435  0.4415301 ]
0.5020570824994548


#### 15. Create a 2d array with 1 on the border and 0 inside

In [21]:
a=np.ones((4,4))
#print(a)
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [22]:
a=np.random.random((3,3))
#print(a)
z=np.zeros(3)
#print(z)
a=np.vstack((z,a))
a=np.vstack((a,z))
#print(a)
zv=np.zeros((5,1))
#print(zv)
a=np.hstack((zv,a))
a=np.hstack((a,zv))
print("Final Output :")
print(a)

Final Output :
[[0.         0.         0.         0.         0.        ]
 [0.         0.66455304 0.888656   0.16300839 0.        ]
 [0.         0.005003   0.46194632 0.26697637 0.        ]
 [0.         0.92700681 0.73719024 0.75399624 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
a = np.diag([x for x in range(1,5)], k = -1)
print (a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
a=np.zeros((8,8))
#print(a)
a[0::2,0::2]=1
#print(a)
a[1::2,1::2]=1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
