In [1]:
import numpy as np

# Basic queries on a numpy Array

In [2]:
a=np.array([[[1,1,1,1],[2,2.6,2,2],[3,'a',3,3]],[[4,4+2j,4,4],[5,5,5,5],[6,6,6,6]]])
print(a)
print("Size is",a.size)
print("Type is",type(a))
print("Shape is",a.shape)
print("N dimensions",a.ndim)
print("Elements type",a.dtype)

[[['1' '1' '1' '1']
  ['2' '2.6' '2' '2']
  ['3' 'a' '3' '3']]

 [['4' '(4+2j)' '4' '4']
  ['5' '5' '5' '5']
  ['6' '6' '6' '6']]]
Size is 24
Type is <class 'numpy.ndarray'>
Shape is (2, 3, 4)
N dimensions 3
Elements type <U32


# Creation Of Array with Tuple

In [3]:
t=(1,2,3)
ar=np.array(t)
print(ar)

[1 2 3]


# Array creation on the go

In [4]:
print(np.zeros((3,4),dtype=int))
print(np.ones((3,4)))
print(np.eye(3))
np.random.random((2,3)) #generates [0-1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[0.24182137, 0.12837512, 0.68509286],
       [0.33709047, 0.16757063, 0.43530164]])

# 1D array creation

In [5]:
print(np.arange(0,20,2))
print(np.arange(18,-2,-2))
print(np.linspace(0,20,10)) # last argument indicates no of values to be printed with equal division of the inclusive interval

[ 0  2  4  6  8 10 12 14 16 18]
[18 16 14 12 10  8  6  4  2  0]
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


# Reshaping of the array

In [6]:
re=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(re.reshape((2,2,3)))
print(re.flatten())
print(re)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Slicing of the numpy array

In [7]:
slicing=np.array([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13,14,15,16]])
print(slicing[1: , 2:4])
print(slicing[1: , :4:2]) #Step size is mentioned  s[startRow:endRow+1:rowStep or incremental ,startcoloumn:endcoloumn+1:coloumnStep or incremental]
print(slicing)

[[ 7  8]
 [11 12]
 [15 16]]
[[ 5  7]
 [ 9 11]
 [13 15]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# conditional indexing

In [8]:
conditional=np.array([[ 1,  -2,  -3,  4],
         [ -5,  6,  -7,  -8],
         [ 9, 10, 11, -12],
         [13,-14,-15,16]])
print(conditional)
cond=conditional>0
conditional=conditional[cond]
print(conditional)

[[  1  -2  -3   4]
 [ -5   6  -7  -8]
 [  9  10  11 -12]
 [ 13 -14 -15  16]]
[ 1  4  6  9 10 11 13 16]


# Broadcasting

In [9]:
a=np.array([[1,2,3,14],[5,6,7,18],[9,10,11,12]])
print(a+1)
print(a-1)
print(a*2)
print(a.T)
print(a.max())
print(a.max(axis=1))#row wise
print(a.max(axis=0))#coloumn wise
# similarly min
print(a.sum())
print(a.sum(axis=0)) # coloumn wise
print(a.cumsum(axis=1)) # row wise

[[ 2  3  4 15]
 [ 6  7  8 19]
 [10 11 12 13]]
[[ 0  1  2 13]
 [ 4  5  6 17]
 [ 8  9 10 11]]
[[ 2  4  6 28]
 [10 12 14 36]
 [18 20 22 24]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [14 18 12]]
18
[14 18 12]
[ 9 10 11 18]
98
[15 18 21 44]
[[ 1  3  6 20]
 [ 5 11 18 36]
 [ 9 19 30 42]]


# Operations on matrices

In [10]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a*b) #cartisian product
print(a.dot(b))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


# Universal Functions

In [11]:
a=np.array([0,np.pi/2,np.pi])
print(np.sin(a))
print(np.exp(a))
print(np.cos(a))
a=np.array([1,2,3,4])
print(np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[1.         1.41421356 1.73205081 2.        ]


# Sorting

In [12]:
a=np.array([[9,4,7,3],[8,2,5,4],[6,1,85,32]])
print(np.sort(a))
print(np.sort(a,axis=0)) # coloumn wise sort
print(np.sort(a,axis=1)) #row wise sort
print(np.sort(a,axis=None,kind='mergesort')) # sort entire nd flatten

[[ 3  4  7  9]
 [ 2  4  5  8]
 [ 1  6 32 85]]
[[ 6  1  5  3]
 [ 8  2  7  4]
 [ 9  4 85 32]]
[[ 3  4  7  9]
 [ 2  4  5  8]
 [ 1  6 32 85]]
[ 1  2  3  4  4  5  6  7  8  9 32 85]


# Stacking

In [13]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]
print(np.vstack((a,b)))
print(np.hstack((a,b)))
c=[10,20]
print(np.column_stack((a,c)))
print(np.concatenate((a,b),1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 1  2 10]
 [ 3  4 20]]
[[1 2 5 6]
 [3 4 7 8]]


# Splitting

In [14]:
a=np.array([[1,2,3,4,5,6],[2,4,6,8,10,12]])
print(np.hsplit(a,3))
print(np.vsplit(a,2))

[array([[1, 2],
       [2, 4]]), array([[3, 4],
       [6, 8]]), array([[ 5,  6],
       [10, 12]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 2,  4,  6,  8, 10, 12]])]


# Statistical Functions

In [15]:
a=np.array([[1,3,1,5,5,6],[3,5,1,5,8,4],[2,5,8,9,3,1]])
# Min or Max
print(np.min(a))
print(np.min(a,axis=1))
print(np.min(a,axis=0))

1
[1 1 1]
[1 3 1 5 3 1]


### Mean

In [16]:
print(np.mean(a))
print(np.mean(a,axis=1))
print(np.mean(a,axis=0))

4.166666666666667
[3.5        4.33333333 4.66666667]
[2.         4.33333333 3.33333333 6.33333333 5.33333333 3.66666667]


### Median

In [17]:
print(np.sort(a,axis=None))
print(np.median(a))
print(a)
print(np.median(a,axis=1))
print(np.median(a,axis=0))

[1 1 1 1 2 3 3 3 4 5 5 5 5 5 6 8 8 9]
4.5
[[1 3 1 5 5 6]
 [3 5 1 5 8 4]
 [2 5 8 9 3 1]]
[4.  4.5 4. ]
[2. 5. 1. 5. 5. 4.]


### weighted average

In [18]:
w=np.ones((3,6))
print(np.average(a,weights=w))

4.166666666666667


### Standard Deviation and varience

In [19]:
m=np.mean(a)
dev=np.sqrt(np.mean(abs(a-m)**2))
print(dev)
print(np.std(a))
v=dev**2
print(v)
print(np.var(a))

2.455153310442706
2.455153310442706
6.027777777777778
6.027777777777778


# Random

In [20]:
print(np.random.random()) #Random value in between [0,1)
print(np.random.randint(1,100,(3,3))) #Random value in between [1,100)
print(np.random.rand(5,3)) # Generates array of size 5,3
print(np.random.choice([2,6,8,10],3))
#print(np.random.randrange(4,100,5)) #generates any number with 4+5*i in between 4 to 99
print(np.random.seed(10))
print(np.random.random())
print(np.random.seed(10))
print(np.random.random()) #got same random value
arr = np.arange(10)
np.random.shuffle(arr)
arr

0.35872973194921665
[[ 4 71 56]
 [70 61 43]
 [60 36 86]]
[[0.88465803 0.17041082 0.57484309]
 [0.42240133 0.15127115 0.57661975]
 [0.33982545 0.55110775 0.22691666]
 [0.96585492 0.40494821 0.82027045]
 [0.67415935 0.15664837 0.91093887]]
[2 6 6]
None
0.771320643266746
None
0.771320643266746


array([2, 6, 8, 5, 7, 9, 3, 1, 0, 4])